name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install --no-fund --no-audit

      - name: TypeScript check
        run: npm run plugin:typecheck

      - name: Build plugin
        run: npm run plugin:build

      - name: Run plugin tests
        run: npm run plugin:test
